"""Note 添加 visit 字段

Revision ID: 54a99c1aab6e
Revises: b8926239da4b
Create Date: 2025-11-21 20:32:26.993775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a99c1aab6e'
down_revision: Union[str, Sequence[str], None] = 'b8926239da4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit', sa.Integer(), server_default='0', nullable=True, comment='访问次数'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('visit')

    # ### end Alembic commands ###
