"""general

Revision ID: 7ec84cc6a4ca
Revises: 2719f552a773
Create Date: 2025-11-23 22:46:44.142706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec84cc6a4ca'
down_revision: Union[str, Sequence[str], None] = '2719f552a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_content'), ['content'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_mimetype'), ['mimetype'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_temporary_uuid'), ['temporary_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_temporary_uuid'))
        batch_op.drop_index(batch_op.f('ix_attachment_size'))
        batch_op.drop_index(batch_op.f('ix_attachment_mimetype'))
        batch_op.drop_index(batch_op.f('ix_attachment_filename'))
        batch_op.drop_index(batch_op.f('ix_attachment_content'))

    # ### end Alembic commands ###
