"""Tag name unique

Revision ID: b8926239da4b
Revises: 2543bf771600
Create Date: 2025-11-21 03:50:38.665482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8926239da4b'
down_revision: Union[str, Sequence[str], None] = '2543bf771600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint('name_tags_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('name_tags_name', type_='unique')

    # ### end Alembic commands ###
