"""add foreignkey

Revision ID: e7b280c31a7d
Revises: d33ff4160e7f
Create Date: 2025-12-11 21:49:52.909855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b280c31a7d'
down_revision: Union[str, Sequence[str], None] = 'd33ff4160e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_id', sa.Integer(), nullable=True, comment='特别使用，允许为空'))
        batch_op.create_foreign_key("fk_tag_note_id", 'note', ['note_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint("fk_tag_note_id", type_='foreignkey')
        batch_op.drop_column('note_id')

    # ### end Alembic commands ###
